# import numpy module and define array

In [3]:
#Import numpy Module
import numpy

#Define Array
array = numpy.array([1,2,3])
print(array)

In [5]:
#Import numpy Module
import numpy as np

#Define Array
array = np.array([12,13,14])
print(array)
List = [1,4,6,7,8]
array2 = np.array(List)
print(array2)

[12 13 14]
[1 4 6 7 8]


In [12]:
#Define Matrix
List = [[1,2,3],[4,5,6]]
matrix = np.array(List)
print(matrix)

#find row_Number * Column_Number
x,y = matrix.shape
print('Matrix Shape is: {0} x {1}, {0} row and {1} comulm'.format(x,y))

[[1 2 3]
 [4 5 6]]
Matrix Shape is: 2 x 3, 2 row and 3 comulm


In [19]:
#Find out the type of array
print(matrix.dtype)
#Check Dimention
print('The Dimention of array is: {} Dimention'.format(matrix.ndim))

int32
The Dimention of array is: 2 Dimention


In [45]:
#define array in numpy array
print(np.arange(21))
print(np.arange(11,21))
print(np.arange(0,21,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [23]:
#Define a array of number and normal array
normalArray = range(10000)
numpyArray = np.arange(10000)
print(normalArray)
print(numpyArray)

range(0, 10000)
[   0    1    2 ... 9997 9998 9999]


In [25]:
#Time comparison between  normal loop and numpy loop
%timeit [i**3 for i in normalArray]
%timeit numpyArray**3

17 ms ± 548 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
93.6 µs ± 1.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [40]:
l1 = range(10000)
l2 = [i**2 for i in l1]
#normal
%timeit list(map(lambda x,y: x+y,l1,l2))
#using numpy
arr1 = np.array(l1)
arr2 = np.array(l2)
%timeit arr1 + arr2

6.74 ms ± 963 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
30.2 µs ± 840 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Define Matrix

In [63]:
#Define zeros matrix
zero = np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [64]:
#Define One Mateix
one = np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [65]:
#Define identity matrix
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
#Define custom matrix
custom = np.full((3,4),2.2)
print(custom)

[[2.2 2.2 2.2 2.2]
 [2.2 2.2 2.2 2.2]
 [2.2 2.2 2.2 2.2]]


In [70]:
#Define tile matrix
v = np.array([1,2,4])
np.tile(v,(3,2))

array([[1, 2, 4, 1, 2, 4],
       [1, 2, 4, 1, 2, 4],
       [1, 2, 4, 1, 2, 4]])

In [81]:
#Define Random matrix
value = np.random.random() #Generate a value between 0-1 number
print(value,'\n')
matrix = 50*np.random.random([3,4])
print(matrix)

0.7741019720762491 

[[28.68760674 18.63629342  4.56567266 41.43425186]
 [ 0.9751311  39.61101987 34.31414759  1.95740699]
 [42.39969669 13.33441526 30.53509591 31.72754203]]


In [83]:
#Create a array, which are equale distance between near two value
np.linspace(1,50,20)

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [86]:
#Reshape any array
dimention = np.arange(18).reshape(3,2,3)
print(dimention)
dimention.shape

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


(3, 2, 3)

In [95]:
#indexing multiple array
arr = np.array([15,45,98,34,12,87,67])
print(arr[0])
print(arr[[0,5,6]])

15
[15 87 67]


In [98]:
#find sum and median
print(np.sum(arr))
print(np.median(arr))
print(np.std(arr))

358
45.0
31.40258666064934


In [105]:
#doc product between two matrix
mat = np.arange(1,7).reshape(2,3)
mat2 = mat.T #transposing
dotPro = mat.dot(mat2)
dotPro

array([[14, 32],
       [32, 77]])

In [110]:
#Logical AND & OR
arr1 = np.array([1,1,1,1,0], dtype = bool)
arr2 = np.array([0,1,0,0,0], dtype = bool)
print(np.logical_and(arr1,arr2))
print(np.logical_or(arr1,arr2))

[False  True False False False]
[ True  True  True  True False]


In [118]:
#sum row or coulm
arr = np.array([[1,6,7],[9,4,7]])
print(arr.sum())
print('Column wise:',arr.sum(axis=0)) #Column wise
print('Row wise',arr.sum(axis=1)) #Row wise
#find max value
print('Max value:',arr.max())

34
Column wise: [10 10 14]
Row wise [14 20]
Max value: 9
